name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # dijalankan setiap hari pukul 00:00 UTC
  workflow_dispatch:    # bisa dijalankan manual dari tab Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: AhmadRendi
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Upload animation
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
